name: site build

on:
  push:
  workflow_dispatch:

jobs:

  Docs:
    uses: cumberland-cloud/workflows/.github/workflows/gh-pages.yaml@master
    with:
      TF_DOCS: false
      NO_CACHE: true
      LATEX: true
      PYTHON_MATHLIBS: true
